# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
minify_html: true

# Dependencies
#markdown:         redcarpet
highlighter:      rouge # pygments

# Permalinks
#permalink:        /:categories/:year/:month/:title # pretty
#permalink:        /:title # pretty
# Site settings
title: Roy Lake Resort, LLC.
email:  info@RoyLakeResort.com
description: > # this means to ignore newlines until "baseurl:"
  Roy Lake Resort & Lodge is a family vacation destination for family fun, recreation,
  fishing and hunting in North East South Dakota. Located in Roy Lake State Park. 
  Excellent fishing all year round and waterfowl, pheasant, turkey & deer hunting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

exclude: [node_modules, gulpfile.js, package.json, run.bat]